const details = [
  {
    id: 1,
    image: "./images/landcruiser.jpg",
    company: "Land Cruiser",
    model: "2029",
    feature: 9,
    price: 100,
    type: "car",
  },
  {
    id: 2,
    image: "./images/ford.jpg",
    company: "Ford",
    model: "2028",
    feature: 8,
    price: 200,
    type: "car",
  },
  {
    id: 3,
    image: "./images/bmw.jpg",
    company: "BMW",
    model: "2027",
    feature: 7,
    price: 300,
    type: "car",
  },
  {
    id: 4,
    image: "./images/rangerover.jpg",
    company: "Range Rover",
    model: "2026",
    feature: 6,
    price: 400,
    type: "car",
  },
  {
    id: 5,
    image: "./images/tesla.jpg",
    company: "Tesla",
    model: "2025",
    feature: 5,
    price: 500,
    type: "car",
  },
  {
    id: 6,
    image: "./images/rollsroyce.jpg",
    company: "Rolls Royce",
    model: "2025",
    feature: 7,
    price: 500,
    type: "car",
  },
  {
    id: 7,
    image: "./images/bullet.jpg",
    company: "Bullet",
    model: "2025",
    feature: 2,
    price: 500,
    type: "bike",
  },
  {
    id: 8,
    image: "./images/ktm.jpg",
    company: "Duke",
    model: "2025",
    feature: 2,
    price: 500,
    type: "bike",
  },
  {
    id: 9,
    image: "./images/ninja.jpg",
    company: "Ninja",
    model: "2025",
    feature: 1,
    price: 500,
    type: "bike",
  },
  {
    id: 10,
    image: "./images/yamaha.jpg",
    company: "Yamaha",
    model: "2025",
    feature: 2,
    price: 500,
    type: "bike",
  },
  {
    id: 11,
    image: "./images/benelli.jpg",
    company: "Benelli",
    model: "2025",
    feature: 2,
    price: 500,
    type: "bike",
  },
];
export default details;
